name: PushAction

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - .github/workflows/pullrequest.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine image tag
        run: |
          IMAGE_TAG=$(echo "${{ github.event.after }}" | cut -c 1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "amd64, arm64/v8"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            linaroits/jekyllsitebuild:${{ env.IMAGE_TAG }}
            linaroits/jekyllsitebuild:latest
          build-args: |
            bamboo_build=${{ env.IMAGE_TAG }}
